### ISSUE TITLE
Amplify UI Authenticator not picking up authorisation code from Cognito HostedUI redirect

### ISSUE THREAD

**Issue by Pylinho** [aws-amplify/amplify-js#12965]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Version

v6

### Amplify Categories

auth

### Backend

Other

### Environment information

<details>

```
# Put output below this line
    @aws-amplify/ui-react: ^6.1.2 => 6.1.2
    @aws-amplify/ui-react-internal:  undefined ()
    aws-amplify: ^6.0.13 => 6.0.13
    aws-amplify/adapter-core:  undefined ()
    aws-amplify/analytics:  undefined ()
    aws-amplify/analytics/kinesis:  undefined ()
    aws-amplify/analytics/kinesis-firehose:  undefined ()
    aws-amplify/analytics/personalize:  undefined ()
    aws-amplify/analytics/pinpoint:  undefined ()
    aws-amplify/api:  undefined ()
    aws-amplify/api/server:  undefined ()
    aws-amplify/auth:  undefined ()
    aws-amplify/auth/cognito:  undefined ()
    aws-amplify/auth/cognito/server:  undefined ()
    aws-amplify/auth/enable-oauth-listener:  undefined ()
    aws-amplify/auth/server:  undefined ()
    aws-amplify/datastore:  undefined ()
    aws-amplify/in-app-messaging:  undefined ()
    aws-amplify/in-app-messaging/pinpoint:  undefined ()
    aws-amplify/push-notifications:  undefined ()
    aws-amplify/push-notifications/pinpoint:  undefined ()
    aws-amplify/storage:  undefined ()
    aws-amplify/storage/s3:  undefined ()
    aws-amplify/storage/s3/server:  undefined ()
    aws-amplify/storage/server:  undefined ()
    aws-amplify/utils:  undefined ()
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    react-router-dom: ^6.21.1 => 6.21.2
    react-scripts: ^5.0.1 => 5.0.1
  npmGlobalPackages:
    @aws-amplify/cli: 12.10.1
    npm-check-updates: 16.14.11
    serve: 14.2.1

```

</details>

### Describe the bug

In a React 18 application, I am using aws-amplify 6.0.13 to handle authentication with Cognito. This is working fine for sign ins where a user is inputting there login details themselves, but isn't working for SSO logins managed via Cognito's Hosted UI. Let me describe my setup.

My amplify is configured as so in my React application:

```
import { Amplify } from 'aws-amplify';
import { defaultStorage } from 'aws-amplify/utils';
import { cognitoUserPoolsTokenProvider } from 'aws-amplify/auth/cognito';

export default function amplifyConfigure() {
  Amplify.configure({
    Auth: {
      Cognito: {
            identityPoolId: myIdPoolId,
            region: myRegion,
            userPoolId: myUserPoolId,
            userPoolClientId: myUserpoolAppClientId,
            loginWith {
                  oauth: {
                      domain: myOAuthDomain,
                      scopes: [ "email", "profile", "openid"],
                      redirectSignIn: "http://localhost:3000/",
                      redirectSignOut: "http://localhost:3000/",
                      responseType: "code",
                  }
            }
      }
    },
    Storage:{
      AWSS3: {
        identityPoolId: myIdPoolId,
        region: myRegion,
        bucket: myS3BucketName
      }
    }
  });

  cognitoUserPoolsTokenProvider.setKeyValueStorage(defaultStorage);
}
```

for which I have anonymised the inputs. amplifyConfigure() is called in my index.js file.

I have a HostedUI in Cognito, which is configured to redirect back to the root directory of my application with an authorisation code grant. When debugging locally, I can see that the user is being authenticated in the HostedUI and the auth code is being attached by the Hosted UI correctly, as I get redirected to http://localhost:3000/?code={code}. However, this code is not then being traded for the authentication tokens with Cognito, as there is no further activity in the developer console in my browser.

I have confirmed that the redirect sign in and sign out URLs are configured identically in both my application code for the Amplify.configure() setup and the Hosted UI, so I have ruled out this as the issue. What could be causing Amplify to not trade the code for the authentication token in my application?

I have tried importing and using Hub to listen for auth events, which has confirmed to me that the code is definitely not being taken and used:

```
import { Hub } from 'aws-amplify/utils';

Hub.listen('auth', (data) => {
  const { payload } = data;
  this.onAuthEvent(payload);
  console.log(
    'A new auth event has happened: ',
    data.payload.data.username + ' has ' + data.payload.event
  );
});
```

and can see from my browser dev tools that no calls are being made to Cognito from my application after being redirected.

Just to note, this issues has arisen as we have recently upgraded from amplify v5, where we had our components wrapped with withAuthenticator(), where the SSO for our clients who used it was set up and working just fine through the Cognito HostedUI and aws-amplify setup.

I have raised the issue both here and over at https://github.com/aws-amplify/amplify-ui, as I was unsure which specifically the bug would relate to.

### Expected behavior

The Authenticator component takes the authorisation code automatically and uses it to authenticate the user with Cognito and login in our application.

### Reproduction steps

N.A.

Too complex and application specific for me to provide a reproducible example, unfortunately.

### Code Snippet

My App.js file returns:
```javascript
// Put your code below this line.
return (
    <ThemeProvider theme={theme}> 
      <Authenticator components={components}>
        <UserProvider>
          <MyRouting/>
        </UserProvider>
      </Authenticator>
    </ThemeProvider>
  );
```
where MyRouting contains the routing for my application.

I can provide the theme and components objects if necessary, but components just contains a Header with a logo.

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Manual configuration

```
{
    Auth: {
      Cognito: {
            identityPoolId: myIdPoolId,
            region: myRegion,
            userPoolId: myUserPoolId,
            userPoolClientId: myUserpoolAppClientId,
            loginWith {
                  oauth: {
                      domain: myOAuthDomain,
                      scopes: [ "email", "profile", "openid"],
                      redirectSignIn: "http://localhost:3000/",
                      redirectSignOut: "http://localhost:3000/",
                      responseType: "code",
                  }
            }
      }
    },
    Storage:{
      AWSS3: {
        identityPoolId: myIdPoolId,
        region: myRegion,
        bucket: myS3BucketName
      }
    }
  }
```
