### ISSUE TITLE
Cognito login works on local environment but does not work when built on amplify hosting

### ISSUE THREAD

**Issue by el-sacapuntas** [aws-amplify/amplify-js#13156]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Region

eu-west-2

### Amplify Hosting feature

Build settings

### Describe the bug

Logging in via cognito works on localhost, but when pushed to amplify, the following error is obtained:

`Authentication Error`

Upon loading the login page, the console log outputs the following:

```
_app-d8892833a755eba6a078.js:1 [ERROR] 55:23.221 AuthError - 
            Error: Amplify has not been configured correctly. 
            The configuration object is missing required auth properties.
            This error is typically caused by one of the following scenarios:

            1. Did you run `amplify push` after adding auth via `amplify add auth`?
                See https://aws-amplify.github.io/docs/js/authentication#amplify-project-setup for more information

            2. This could also be caused by multiple conflicting versions of amplify packages, see (https://docs.amplify.aws/lib/troubleshooting/upgrading/q/platform/js) for help upgrading Amplify packages.
        
e._log @ _app-d8892833a755eba6a078.js:1
rightclick.js:25 allow right click processing https://master.dkvoickwj2o4h.amplifyapp.com/
```

When trying to log in, the console outputs:

```
NoUserPoolError: Authentication Error
    at t [as constructor] (_app-xxxxx.js:1:13288)
    at new t (_app-xxxx.js:1:13466)
    at e.rejectNoUserPool (_app-xxxx.js:1:46973)
    at e.signIn (_app-xxxx.js:1:22099)
    at _app-xxxx.js:74:487530
    at l (main-xxxx.js:1:72124)
    at Generator._invoke (main-xxxx.js:1:71912)
    at Generator.next (main-xxxx.js:1:72553)
    at r (_app-xxxx.js:74:653955)
    at s (_app-xxxx.js:74:654158)
```

None of these are seen when running on localhost.

### Expected behavior

For authorised users to be able to log in just as they can in the localhost environment.

### Reproduction steps

1. Build on amplify hosting
2. Login
3. Error

### Build Settings

```yaml
On amplify:

version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*

Local:

{
  "name": "xxxxxxxx",
  "version": "5.0.2",
  "author": "xxxxxxxxxx",
  "private": true,
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start",
    "export": "next export",
    "build-export": "next build && next export",
    "lint": "next lint",
    "lint-fix": "next lint --fix"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "dependencies": {
    "@auth0/auth0-spa-js": "^1.20.1",
    "@emotion/cache": "^11.7.1",
    "@emotion/react": "^11.8.2",
    "@emotion/server": "^11.4.0",
    "@emotion/styled": "^11.8.1",
    "@fullcalendar/common": "^5.9.0",
    "@fullcalendar/core": "^5.9.0",
    "@fullcalendar/daygrid": "^5.9.0",
    "@fullcalendar/interaction": "^5.9.0",
    "@fullcalendar/list": "^5.9.0",
    "@fullcalendar/react": "^5.9.0",
    "@fullcalendar/timegrid": "^5.9.0",
    "@fullcalendar/timeline": "^5.9.0",
    "@material-ui/core": "^4.12.3",
    "@mui/icons-material": "^5.5.1",
    "@mui/lab": "^5.0.0-alpha.74",
    "@mui/material": "^5.5.2",
    "@mui/system": "^5.5.2",
    "@react-pdf/renderer": "^1.6.17",
    "@reduxjs/toolkit": "^1.8.0",
    "@types/lodash": "^4.14.180",
    "@types/node": "16.11.6",
    "@types/nprogress": "^0.2.0",
    "@types/react": "17.0.33",
    "@types/react-beautiful-dnd": "^13.0.0",
    "@types/react-draft-wysiwyg": "^1.13.4",
    "@types/react-redux": "^7.1.23",
    "@types/yup": "^0.29.11",
    "apexcharts": "^3.33.2",
    "aws-amplify": "^3.0.20",
    "date-fns": "^2.28.0",
    "draft-js": "^0.11.7",
    "firebase": "^8.10.1",
    "formik": "^2.2.7",
    "gray-matter": "^4.0.3",
    "i18next": "^19.8.7",
    "lodash": "^4.17.21",
    "lodash.debounce": "^4.0.8",
    "luxon": "^2.3.1",
    "next": "^11.1.3",
    "nprogress": "^0.2.0",
    "numeral": "^2.0.6",
    "prop-types": "^15.8.1",
    "react": "^17.0.1",
    "react-apexcharts": "^1.4.0",
    "react-beautiful-dnd": "^13.0.0",
    "react-dom": "^17.0.1",
    "react-draft-wysiwyg": "^1.14.5",
    "react-dropzone": "^11.7.1",
    "react-hot-toast": "^1.0.2",
    "react-i18next": "^11.16.2",
    "react-markdown": "^5.0.3",
    "react-quill": "2.0.0-beta.4",
    "react-redux": "^7.2.4",
    "react-syntax-highlighter": "^15.5.0",
    "redux": "^4.1.0",
    "redux-devtools-extension": "^2.13.9",
    "redux-thunk": "^2.4.1",
    "simplebar": "^5.3.6",
    "simplebar-react": "^2.3.6",
    "stylis": "^4.0.13",
    "stylis-plugin-rtl": "^2.1.1",
    "typescript": "4.4.4",
    "uuid": "^8.3.2",
    "yup": "^0.32.11"
  },
  "devDependencies": {
    "@svgr/webpack": "^5.5.0",
    "@types/luxon": "^2.3.1",
    "eslint": "^7.32.0",
    "eslint-config-next": "12.0.3-canary.7",
    "next-transpile-modules": "^9.0.0"
  }
}
```
