### ISSUE TITLE
Lambda functions using the node.js 6.10 runtime - EOL

### ISSUE THREAD

**Issue by srbartlett** [aws-amplify/amplify-js#2925]
** Which Category is your question related to? **
Amplify Auth

** What AWS Services are you utilizing? **
Cognito 

** Provide additional details e.g. code snippets **
I recently received an email from AWS support stating that Lambda functions in my account are using Node.js 6.10 which will soon be EOL, they suggest migrating to a new version of Node runtime.

The functions in question related to the Lambdas deployed as part of the Amplify Auth CloudFormation stack.  

Code snippet below:  Are there plans to migrate to a newer runtime?  What is the best strategy to change the runtime version this should the Amplify CLI not be updated before the deadline of April 30th 2019
 
```  
UserPoolClientLambda:
  # Lambda which gets userpool app client config values
  # Depends on UserPool for id
  # Depends on UserPoolClientRole for role ARN
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        ZipFile: !Join
          - |+
          - - 'const response = require(''cfn-response'');'
            - 'const aws = require(''aws-sdk'');'
            - 'const identity = new aws.CognitoIdentityServiceProvider();'
            - 'exports.handler = (event, context, callback) => {'
            - ' if (event.RequestType == ''Delete'') { '
            - '   response.send(event, context, response.SUCCESS, {})'
            - ' }'
            - ' if (event.RequestType == ''Update'' || event.RequestType == ''Create'') {'
            - '   const params = {'
            - '     ClientId: event.ResourceProperties.clientId,'
            - '     UserPoolId: event.ResourceProperties.userpoolId'
            - '   };'
            - '   identity.describeUserPoolClient(params).promise()'
            - '     .then((res) => {'
            - '       response.send(event, context, response.SUCCESS, {''appSecret'': res.UserPoolClient.ClientSecret});'
            - '     })'
            - '     .catch((err) => {'
            - '       response.send(event, context, response.FAILURE, {err});'
            - '     });'
            - ' }'
            - '};'
      Handler: index.handler
      Runtime: nodejs6.10
      Timeout: '300'
      Role: !GetAtt
        - UserPoolClientRole
        - Arn
    DependsOn: UserPoolClientRole
```
