### ISSUE TITLE
SignUp with Custom Attributes throws errors

### ISSUE THREAD

**Issue by rossgeesman** [aws-amplify/amplify-js#2958]
**Describe the bug**
I have created a Cognito User Pool and Identity Pool via Cloud Formation templates using the Serverless Framework. The schema looks like this:
```
      Schema:
        - Name: family_name
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: given_name
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: confirmed_email
          AttributeDataType: Boolean
          Mutable: true
          Required: false
```
Signup was working fine until I added the confirmed_email attribute and added it to signup. This results in a SerializationException being raised. The only way I can create the user with the custom attribute is to append `custom` to the key so that `confirmed_email` becomes `custom:confirmed_email` and the boolean will only work as a string.

**To Reproduce**
1. Use above schema to add attributes to a Cognito User Pool. Then attempt to sign up a user with the following:
```
Auth.signUp({
      username: email,
      password: password,
      attributes: {
        given_name: given_name,
        family_name: family_name,
        confirmed_email: false
      },
 })
```
2. This will result in the following error:
```
{code: "SerializationException", name: "SerializationException", message: "class java.lang.Boolean can not be converted to an String"}
```
3. Now sign up a user with this code:
```
Auth.signUp({
      username: email,
      password: password,
      attributes: {
        given_name: given_name,
        family_name: family_name,
       'custom: confirmed_email': 'false'
      },
 })
```
You should not observe the error and the user should be created successfully.

**Expected behavior**
I expect `Auth.signUp()` to accept custom attributes as a regular javascript object as shown here: https://aws.amazon.com/blogs/mobile/aws-amplify-adds-support-for-custom-attributes-in-amazon-cognito-user-pools/
