### ISSUE TITLE
API module doesn't work with custom domain

### ISSUE THREAD

**Issue by marekk657** [aws-amplify/amplify-js#3225]
**Describe the bug**
I'm using aws-amplify API module to make requests to API Gateway. But it seems like aws-amplify can't make requests to API gateway with custom domain. While doing `curl -k api.mydomain.com/path` works.

aws-amplify API module works fine if i use AWS uri: `[hash].execute-api.[region].amazonaws.com`

From browser's console i can only see 
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.mydomain.com. (Reason: CORS request did not succeed). 
Error: "Network Error"
`

So it can't be the issue with CORS as aws' default uri works fine. 

I've set up custom domain for API Gateway with serverless framework configuration.
Custom domain config:
```yaml
customDomain:
     domainName: api.mydomain.com
     basePath: ''
     stage: ${self:provider.stage}
     createRoute53Record: true
     endpointType: edge
```
aws-amplify config:
```javascript
API: {
    endpoints: [
      {
        name: 'baseEndpoint',
        endpoint: process.env.VUE_APP_API_BASE,
        region: process.env.VUE_APP_REGION,
        custom_header: () => {
          return {
            'x-api-key': process.env.VUE_APP_API_KEY
          }
        }
      }
    ]
  }
```

Requests are done like this:
```javascript
 const init = {
        queryStringParameters: {
          param1: value1
        }
      }
return API.get('baseEndpoint', '/mypath', init).catch(e => {console.log(e)})
```
