### ISSUE TITLE
Signup with an invalid password gives username error message

### ISSUE THREAD

**Issue by philiiiiiipp** [aws-amplify/amplify-js#4177]
**Describe the bug**
If you signup with a password that does not satisfy the password constrains the message since #4102 always refers to the username. 

**To Reproduce**
Signup with an invalid password

**Expected behavior**
The message before was "1 validation error detected: Value at 'password' failed to satisfy constraint: Member must have length greater than or equal to 6", where the satisfy constraint depends on your cognito configuration. Which I suppose came straight from cognito and was nice for debugging.

I am wondering why the message needs to be changed at all ? I suppose the frontend should implement the necessary checks before the user signs up.

**Comment by elorzafe** [comment]
@philiiiiiipp I tried the latest amplify and I have the correct message. 

- What is the configuration of the userpool? signup with username, email or phone number?
- Are you using a particular framework or just `Auth.signUp`?

**Comment by philiiiiiipp** [comment]
It is the latest version as of now.

```
npm list @aws-amplify/auth 
@dh/sfa-api@0.0.99 /Users/philipp/node/dev/dh/sfa-api
└── @aws-amplify/auth@1.4.2 
```

```
test('Incorrect user request - password to bad', () => {
    const noOp = jest.fn();

    return Auth.signUp({ username: 'test@mydomain.com', password: '123' })
      .then(noOp)
      .catch(e => {
        expect(e.code).toEqual('InvalidParameterException');
        expect(e.message).toEqual(
          "1 validation error detected: Value at 'password' failed to satisfy constraint: Member must have length greater than or equal to 6",
        );
      })
      .then(() => {
        expect(noOp).not.toBeCalled();
      });
  });
```

We signup with email, the CF portion looks like:

```
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: true
            RequireUppercase: true
        AutoVerifiedAttributes:
          - email
        UsernameAttributes:
          - email
        Schema:
          - Name: name
            AttributeDataType: String
            Mutable: true
            Required: true
          - Name: phone
            AttributeDataType: String
            Mutable: true
```

We do use Auth.Signup directly. Its a nodejs integration test.

I am now always getting the same error 

```
Cognito - New User › Incorrect user request - password to bad

    expect(received).toEqual(expected) // deep equality

    Expected: "1 validation error detected: Value at 'password' failed to satisfy constraint: Member must have length greater than or equal to 6"
    Received: "Username could not be created. Please make sure that the username you have entered is between 1 and 128 characters."

      79 |       .catch(e => {
      80 |         expect(e.code).toEqual('InvalidParameterException');
    > 81 |         expect(e.message).toEqual(
         |                           ^
      82 |           "1 validation error detected: Value at 'password' failed to satisfy constraint: Member must have length greater than or equal to 6",
      83 |         );
      84 |       })

      at toEqual (src/cognito/__test__/cognito.test.integration.js:81:27)
```

Which I believe is because of #4102
