### ISSUE TITLE
AccessToken doesn't work for authenticating calls to API GW but IdToken does.

### ISSUE THREAD

**Issue by vgaltes** [aws-amplify/amplify-js#4209]
** Which Category is your question related to? **
Auth
** What AWS Services are you utilizing? **
Cognito
** Provide additional details e.g. code snippets **
Amplify Auth version: 1.4.2
Amplify Api version: 1.2.2

Hi, I've created a simple Cognito User Pool using the serverless framework:
```
CognitoUserPool:
  Type: AWS::Cognito::UserPool
  Properties:
    UserPoolName: ${self:provider.stage}-testauthsls-user-pool
    UsernameAttributes:
      - email
    AutoVerifiedAttributes:
      - email

CognitoUserPoolClient:
  Type: AWS::Cognito::UserPoolClient
  Properties:
    ClientName: ${self:provider.stage}-testauthsls--user-pool-client
    UserPoolId:
      Ref: CognitoUserPool
    GenerateSecret: false
```

And then I created an authenticated API endpoint:
```
helloWorldSecured:
  handler: src/functions/helloWorldSecured.handler
  events:
    - http:
        path: api/helloWorldSecured
        method: get
        cors: true
        authorizer:
          name: authorizer
          arn: arn:aws:cognito-idp:#{AWS::Region}:#{AWS::AccountId}:userpool/eu-west-1_XXXXXXX
```

Then, when I make a call using the API object, if I set up the headers in this way:
```
RequestToSecuredEndpointButton.addEventListener('click', async evt => {
  let myInit = { 
    headers: { Authorization: `Bearer ${(await Auth.currentSession()).getAccessToken().getJwtToken()}` }
}
  await API.get("MyAPIGatewayAPI", '/dev/api/helloWorldSecured', myInit).then(response => {
      console.log(response);
  }).catch(error => {
      console.log(JSON.stringify(error))
  });
});
```
I get a 401 unauthorized back, but if I use the idToken instead
```

RequestToSecuredEndpointButton.addEventListener('click', async evt => {
  let myInit = { 
    headers: { Authorization: `Bearer ${(await Auth.currentSession()).getIdToken().getJwtToken()}` }
}
  await API.get("MyAPIGatewayAPI", '/dev/api/helloWorldSecured', myInit).then(response => {
      console.log(response);
  }).catch(error => {
      console.log(JSON.stringify(error))
  });
});
```
I get a 200 Ok.

Why I can't use the AccessToken?
