### ISSUE TITLE
PreAuthentication trigger not triggered

### ISSUE THREAD

**Issue by armandabric** [aws-amplify/amplify-js#5318]
** Which Category is your question related to? **
Auth

** What AWS Services are you utilizing? **
Cognito

** Provide additional details e.g. code snippets **

I have an issue with the Cognito PreAuthentication trigger not triggered when an user sign-in

We are using a Cognito user pool with only  `CUSTOM_AUTH_FLOW_ONLY` auth to do a passwordless authentication system. 

I my CloudFormation template I have configured a lambda to handle the trigger :

```yaml
  # ...

  PreAuthentication:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/lambda-triggers/pre-authentication/
      Handler: pre-authentication.handler
      Runtime: nodejs12.x

  # ...

PreAuthenticationInvocationPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt PreAuthentication.Arn
      Principal: cognito-idp.amazonaws.com
      SourceArn: !GetAtt UserPool.Arn

  # ... 

  UserPool:
    Type: "AWS::Cognito::UserPool"
    Properties:
      UserPoolName: !Ref UserPoolName
      Schema: # ...
      Policies: # ...
      UsernameAttributes:
        - email
      MfaConfiguration: "OFF"
      LambdaConfig:
        CreateAuthChallenge: !GetAtt CreateAuthChallenge.Arn
        DefineAuthChallenge: !GetAtt DefineAuthChallenge.Arn
        PreSignUp: !GetAtt PreSignUp.Arn
        PreAuthentication: !GetAtt PreAuthentication.Arn # Here 
        VerifyAuthChallengeResponse: !GetAtt VerifyAuthChallengeResponse.Arn
        PostAuthentication: !GetAtt PostAuthentication.Arn

# ...

  UserPoolClient:
    Type: "AWS::Cognito::UserPoolClient"
    Properties:
      ClientName: email-auth-client
      GenerateSecret: false
      UserPoolId: !Ref UserPool
      ExplicitAuthFlows:
        - CUSTOM_AUTH_FLOW_ONLY
```

For now the lambda implementation is useless:

```js
import { CognitoUserPoolTriggerHandler } from "aws-lambda";

export const handler: CognitoUserPoolTriggerHandler = async (
  event,
  context
) => {
  console.log(event, context);

  // return event;
  throw new Error("Is this really executed?");
};
```

When I deploy the lambda it appear correctly in the Cognito UI as the registered trigger. 

But impossible to have the function to be executed on sign in (nor sign up):

```js 
const newCognitoUser = await AmplifyAuth.signIn({
    username: email,
    password: "",
    validationData: { some_data: "foo_bar" },
});

# No PreAuthentication lambda triggered
# Others triggers works perfectly.
```

Is this an issue Aplify or is that an issue with my understanding of the auth process?
