### ISSUE TITLE
Upgrading AWS Amplify from 2.3.0 to 3.0.13 breaks TypeScript compilation

### ISSUE THREAD

**Issue by frederikprijck** [aws-amplify/amplify-js#5949]
**Describe the bug**
On a project, that has been using AWS Amplify succesfully using aws-amplify `2.3.0`, TypeScript compilation breaks as soon as I upgrade `aws-amplify` to `3.0.13`.

The TypeScript compilation error that I get is the following:

```
libs/api/src/lib/api.service.ts:6379:68 - error TS2352: Conversion of type 'Promise<GraphQLResult<object>> | Observable<object>' to type 'Observable<OnDeleteReportSubscription>' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Type 'Observable<object>' is missing the following properties from type 'Observable<OnDeleteReportSubscription>': [Symbol.observable], concat
```

Things I've tried so far:

- removing package-lock.json
- removing node_modules
- npm install everything again
- amplify codegen

=> TypeScript compilation still throws the same error.

I also tried:
- removing .graphqlconfig.yml
- regenerating .graphqlconfig.yml using `amplify codegen add`
- Upgrading the amplify CLI to the latest version

=> TypeScript compilation still throws the same error.

**To Reproduce**

1. On a TypeScript project (in my case angular, so using the Angular codegen target) using aws-amplify 2.3.0, run `npm install aws-amplify@3.0.13`
2. Try to compile TypeScript (the API service was originally created with an older Amplify CLI version while the project was using aws-amplify 2.3.0

**Expected behavior**
TypeScript succesfuly compiles after upgrading `aws-amplify`.

**Code Snippet**
Currently, I have no reproduction repository yet. I'm not that familiar with AWS to quickly spin up a new instance for public testing. But I'll do my best to get this.

**Screenshots**
![image](https://user-images.githubusercontent.com/2146903/83336081-1268f180-a2b1-11ea-9cc3-97b38708c87a.png)

**What is Configured?**
This is the .graphqlconfig.yaml file that we are using
```
projects:
  confMatch:
    schemaPath: libs/api/src/graphql/schema.json
    includes:
      - libs/api/src/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: libs/api/src/lib/api.service.ts
        docsFilePath: libs/api/src/graphql
extensions:
  amplify:
    version: 3
```
