### ISSUE TITLE
Type error in Cognito custom Number attribute update

### ISSUE THREAD

**Issue by mrcportillo** [aws-amplify/amplify-js#5978]
The update process for authenticated user attributes on Cognito fails with a casting error for `Number` attributes.
 I created a user pool in Cognito using cloud formation with this schema:

```
        Schema:
          - Name: ackStatement
            AttributeDataType: Number
            Mutable: true
            NumberAttributeConstraints:
              MaxValue: 1
              MinValue: 0
          - Name: stealthMode
            AttributeDataType: Number
            Mutable: true
            NumberAttributeConstraints:
              MaxValue: 1
              MinValue: 0
          - Name: displayName
            AttributeDataType: String
            Mutable: true
            StringAttributeConstraints:
              MaxLength: 20
              MinLength: 3
          - Name: firstName
            AttributeDataType: String
            Mutable: true
            StringAttributeConstraints:
              MaxLength: 20
              MinLength: 3
          - Name: lastName
            AttributeDataType: String
            Mutable: true
            StringAttributeConstraints:
              MaxLength: 20
              MinLength: 3
          - Name: email
            AttributeDataType: String
            Mutable: false
            Required: true
```
When I try to update the user's attributes with: 

```
Auth.updateUserAttributes(user, {
        "custom:displayName": 'some string',
        "custom:stealthMode": 0
      })
```

it fails with the error:

```
{"__type":"SerializationException","Message":"class com.amazon.coral.value.json.numbers.TruncatingBigNumber can not be converted to an String"}
```
If a try to update just strings attributes it works.

I'm using version 3.0.11.
