### ISSUE TITLE
HTTP 400 (MalformedXML) on Storage.vault.put on anything over a few mb

### ISSUE THREAD

**Issue by liebrand** [aws-amplify/amplify-js#6192]
I'm using 
```
const file = evt.target.files[0];
await Storage.vault.put(filename, file, {
  contentType: file.type
});
```

Which seems to work fine on anything of a few MB or so. But as soon as I try something of 10mb or more, it causes an HTTP 400 in the console (although oddly enough, the code returns as if everything is fine - e.g. it doesn't throw an exception).

Is this some multipart problem? If it's not supported, shouldn't it throw an exception? And if it's not supported, how do I upload anything of substantial size?

The 400 response is:
```
<Error><Code>MalformedXML</Code><Message>The XML you provided was not well-formed or did not validate against our published schema</Message><RequestId>C6C279D153F23943</RequestId><HostId>2cVVDj9KiCArATkZfocEdUGHyS0D0jHuxpJyg3KxIJG6KFJT8AdbF+rfwu4cylKXR9P1f+7aZYg=</HostId></Error>
```

My amplify versions:
@aws-amplify/storage@3.2.7
@aws-amplify/api-rest@1.1.0
@aws-amplify/auth@3.2.14
@aws-amplify/core@3.4.0

**Comment by liebrand** [comment]
FYI - I think I've resolved this. The problem was that my s3 bucket did not have the etag exposed in it's CORS configuration. Simple fix, although amplify Storage could have provided a better error I s'pose

In serverless yml:
```
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      # Set the CORS policy
      CorsConfiguration:
        CorsRules:
          -
            AllowedOrigins:
              - '*'
            AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            MaxAge: 3000
            ExposedHeaders:     <----- Make sure to
              - ETag            <----- add this bit
```
