### ISSUE TITLE
Storage get requests fails after changing host

### ISSUE THREAD

**Issue by joeltio** [aws-amplify/amplify-js#6596]
**Describe the bug**
I have a Cloudfront distribution in front of an S3 bucket. To create authenticated URLs, I use `Storage.get` to sign URLs against the S3 bucket, then I change the origin of the URL to Cloudfront's. So, requests are sent to Cloudfront but still signed for the S3 bucket.

I have tried this on AWS SDK and it works fine. However, when using Amplify, I get an error that the signature does not match.

**To Reproduce**

1. Create an AWS Cognito User Pool
2. Create a web client to make API calls
3. Create an AWS Cognito Identity Pool
4. Link the identity pool to the user pool
5. Create an S3 bucket
6. Authorise one of the identities to access the bucket
7. Create a CloudFront distribution
8. Set one of the origins as the S3 bucket and ensure that query parameters are forwareded
9. Configure Amplify with the user pool, identity pool and S3 bucket
10. Sign in using Amplify Auth
11. Create a signed URL with `Storage.get`
12. Test that the URL works and you can retrieve the item
13. Change the bucket origin to the cloudfront's URL. For example `https://my-bucket.s3.us-west-1.com/path/to/obj?...` becomes `https://cloudfront-distribution-url.com/path/to/obj?...`
14. Error: Signature does not match

**Expected behavior**
The object should be retrieved as in step 12.

**Code Snippet**
Here is the code I run:
```javascript
global.fetch = require('node-fetch')
const { Amplify } = require('@aws-amplify/core');
const { Auth } = require('@aws-amplify/auth');
const { Storage } = require('@aws-amplify/storage');

const USERNAME = '';
const PASSWORD = '';

const USER_POOL = {
    id: '',
    region: '',
}

const TEST_ITEM = {
    bucket: '',
    key: '',
    region: '',
}

const storagePrefix = {
    public: '',
    protected: '',
    private: '',
};

function onSignIn(user) {
    Storage.get(TEST_ITEM.key, { customPrefix: storagePrefix }).then(console.log);
}

// Sign in using Amplify
Amplify.configure({
    Auth: {
        region: '',
        mandatorySignIn: true,
        identityPoolId: '',
        userPoolId: '',
        userPoolWebClientId: '',
    },
    AWSS3: {
        bucket: TEST_ITEM.bucket,
        region: TEST_ITEM.region,
    }
});

Auth.signIn({
    username: USERNAME,
    password: PASSWORD,
}).then(onSignIn).catch(console.error);

```

And here is the AWS SDK code I use:
```javascript
global.fetch = require('node-fetch')
const { Amplify } = require('@aws-amplify/core');
const { Auth } = require('@aws-amplify/auth');
const AWS = require('aws-sdk');

const USERNAME = '';
const PASSWORD = '';

const USER_POOL = {
    id: '',
    region: '',
}

const TEST_ITEM = {
    bucket: '',
    key: '',
    region: '',
}

function onSignIn(user) {
    // See https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentity.html#getId-property
    // Slice the payload's "https://" from the URL
    // cognito-idp.${USER_POOL.region}.amazonaws.com/${USER_POOL.id}
    const provider = user.signInUserSession.idToken.payload.iss.slice(8)
    const idToken = user.signInUserSession.idToken.jwtToken;
    AWS.config.credentials = new AWS.CognitoIdentityCredentials({
        IdentityPoolId: '',
        Logins: {
            [provider]: idToken,
        },
    });
    AWS.config.region = TEST_ITEM.region;

    // Setup S3 client
    const s3 = new AWS.S3({
        apiVersion: '2006-03-01',
        region: TEST_ITEM.region,
    });

    // Get object
    const url = s3.getSignedUrl('getObject', {
        Bucket: TEST_ITEM.bucket,
        Key: TEST_ITEM.key,
        Expires: 5*60,
    }, (err, url) => {
        if (err) {
            console.error(err);
            return;
        }

        console.log(url);
    });
}

// Sign in using Amplify
Amplify.configure({
    Auth: {
        region: '',
        mandatorySignIn: true,
        identityPoolId: '',
        userPoolId: '',
        userPoolWebClientId: '',
    },
});

Auth.signIn({
    username: USERNAME,
    password: PASSWORD,
}).then(onSignIn).catch(console.error);

```

**Screenshots**
![signature does not match](https://user-images.githubusercontent.com/5127468/90421274-bc575d80-e0eb-11ea-9eea-ed6bc782baa0.png)

**What is Configured?**
Note that these configuration excerpts are not complete. I have left out connecting user pools to identity pools.

Cloudfront Cloudformation Excerpt:
```
Resources:
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
        - Ref: DomainName
        Origins:
        - Id: my-bucket
          DomainName: !Ref MyBucketDomainName
          S3OriginConfig:
            OriginAccessIdentity: ''
        DefaultCacheBehavior:
          # Removed but required for setting up
        CacheBehaviors:
        - TargetOriginId: my-bucket
          AllowedMethods:
          - GET
          - HEAD
          CachedMethods:
          - GET
          - HEAD
          Compress: true
          DefaultTTL: 300
          ForwardedValues:
            QueryString: true
          PathPattern: /my/path/
          SmoothStreaming: false
          ViewerProtocolPolicy: redirect-to-https
```

User Pool
```
Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: mypool

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    DependsOn: UserPool
    Properties:
      UserPoolId:
        Ref: UserPool
      ClientName:
        Ref: UserPoolClientName
      GenerateSecret: false
      SupportedIdentityProviders:
      - COGNITO
      AllowedOAuthFlows: []
      AllowedOAuthFlowsUserPoolClient: false
      AllowedOAuthScopes: []
      ExplicitAuthFlows: []
      LogoutURLs: []
```

Identity Pool
```
Resources:
  IdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
      - ClientId:
          Ref: UserPoolClientId
        ProviderName:
          Fn::Sub:
          - cognito-idp.${AWS::Region}.amazonaws.com/${poolId}
          - poolId:
              Ref: UserPoolId
        ServerSideTokenCheck: true
      IdentityPoolName: myidpool
```

S3 Bucket:
```
Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-bucket
      AccessControl: Private
      CorsConfiguration:
        CorsRules:
        - AllowedHeaders:
          - '*'
          AllowedMethods:
          - GET
          - PUT
          - HEAD
          - POST
          - DELETE
          AllowedOrigins:
          - http://127.0.0.1:8080
          ExposedHeaders:
          - x-amz-server-side-encryption
          - x-amz-request-id
          - x-amz-id-2
          - ETag
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
  ContentBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ContentBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - s3:GetObject
          Principal:
            AWS: !Ref MyIdentityRoleIAMArn
          Resource:
          - !Sub arn:aws:s3:::$${MyBucket}/my/path/*
```

<details>
  <summary><strong>Environment</strong></summary>

```
  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 3.35 GB / 15.61 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 10.19.0 - /usr/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.4 - /usr/bin/npm
  Browsers:
    Firefox: 79.0
  npmPackages:
    @aws-amplify/auth: ^3.3.4 => 3.3.4 
    @aws-amplify/core: ^3.4.5 => 3.4.5 
    @aws-amplify/storage: ^3.2.12 => 3.2.12 
    aws-appsync: ^4.0.0 => 4.0.0 
    aws-sdk: ^2.732.0 => 2.732.0 
    graphql: ^15.3.0 => 15.3.0 
    graphql-tag: ^2.11.0 => 2.11.0 
    node-fetch: ^2.6.0 => 2.6.0
```

</details>
