### ISSUE TITLE
How to explicitly set accessKeyId and secretAccessKey?

### ISSUE THREAD

**Issue by alexsmartens** [aws-amplify/amplify-js#666]
I'm working on multiple RN projects. For one of the projects I have to use S3 to access the data, and I'm having the following error:
```
{[WARN] 45:38.299 StorageClass - error uploading: Error: Access Denied
    at Request.extractError (blob:http://localhost:8081/393e6cf4-961d-4258-a241…}
```
After rigorous debugging, I figured out that that I'm making request with the credentials of a different project. This is happening despite I explicitly set up awsmobile credentials with `awsmobile configure`.

I tried to set up credentials over again with  `awsmobile configure`, but this did not help (although I saw new credentials while setting `awsmobile configure`). I also tried to follow [AWS.Credentials overview](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Credentials.html)  referred on the [official Amplify documentation page](https://aws.github.io/aws-amplify/media/quick_start)  as follows:
```
Amplify.Credentials = new Amplify.Credentials(accessKeyId = 'myNewAccessKeyId', 
  secretAccessKey = 'myNewSecretAccessKey', 
  sessionToken = null)
```
However, I'm having the following error in this case: `TypeError: _awsAmplify2.default.Credentials is not a constructor`.

Please suggest, how the credentials,  accessKeyId and secretAccessKey in particular, might be changed?

**Comment by mlabieniec** [comment]
@alexsmartens you shouldn't need to do this, perhaps this is an issue with the CLI configuration, @UnleashedMind what do you think?

As for credentials, these are set by Cognito when using Amplify after logging in. They are temporary credentials. It's highly recommended you don't hard code the access key / secret key onto the front end application. The underlying low-level JavaScript SDK is what ultimately sets those credentials with the temporary credentials that are retrieved by cognito. If you were to set them you'd have to set them on the global AWS object, but it's not something that's exposed or able to be done perhaps outside accessing it via something like `window.AWS`: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Credentials.html

**Comment by elorzafe** [comment]
Hi @alexsmartens when you call Amplify.configure(aws_exports); This will load credentials from your cognito identitypool, this could be unauth or auth credentials depending on how did you configure your project. That is why you have different credentials as you are using on awsmobile configure.

How are you trying to upload your file?

**Comment by alexsmartens** [comment]
Hi @elorzafe,
here is how I'm trying to upload my files:
```
    Storage.put(fileName, blob, { contentType: 'image/jpeg' })
    .then(result => {
      console.log('--result')
     console.log(result)
    })
    .catch(err => {});
```

**Comment by alexsmartens** [comment]
@mlabieniec: I think I really might be an issue with CLI configurations

**Comment by alexsmartens** [comment]
I tried to explicitly set up the credentials for testing:
```
  Auth.credentials.accessKeyId="myNewAccessKeyId"
  Auth.credentials.data.Credentials.AccessKeyId="myNewAccessKeyId"
  Auth.credentials.data.Credentials.SecretKey="myNewSecretAccessKey"
  Auth.credentials.secretAccessKey="myNewSecretAccessKey"
```
which caused the following error:
```
{[WARN] 03:16.938 StorageClass - error uploading: Error: The provided token is malformed or otherwise invalid.
    at Request.extractError (blob:http:…}
```

**Comment by elorzafe** [comment]
Can you paste the data inside of awsmobilejs/backend/mobile-hub-project.yml

**Comment by alexsmartens** [comment]
My awsmobilejs/backend/mobile-hub-project.yml:
```
--- !com.amazonaws.mobilehub.v0.Project 
features:
  content-delivery: !com.amazonaws.mobilehub.v0.ContentDelivery 
    attributes:
      enabled: true
      visibility: public-global
    components:
      release: !com.amazonaws.mobilehub.v0.Bucket {}
  mobile-analytics: !com.amazonaws.mobilehub.v0.Pinpoint 
    components:
      analytics: !com.amazonaws.mobilehub.v0.PinpointAnalytics {}
  sign-in: !com.amazonaws.mobilehub.v0.SignIn {}
name: MyName
region: us-west-2
```
