### ISSUE TITLE
Amplify Preview builds are creating duplicated DynamoDB tables and new Cognito Userpools

### ISSUE THREAD

**Issue by joshlongbrake** [aws-amplify/amplify-js#8299]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Next.js

### Amplify APIs

Authentication, GraphQL API

### Amplify Categories

auth, api, hosting

### Environment information

<details>

```
# Put output below this line
System:
    OS: macOS 11.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 661.54 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.12.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.6.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 90.0.4430.212
    Safari: 14.1
  npmPackages:
    @ampproject/toolbox-optimizer:  undefined ()
    @aws-amplify/ui-react: ^1.0.6 => 1.0.7 
    @babel/core:  undefined ()
    @babel/plugin-transform-runtime: ^7.13.15 => 7.13.15 
    @babel/preset-env: ^7.13.15 => 7.14.1 
    @babel/preset-react: ^7.13.13 => 7.13.13 
    @chakra-ui/react: ^1.5.0 => 1.6.0 
    @emotion/react: ^11 => 11.1.5 
    @emotion/styled: ^11 => 11.3.0 
    @testing-library/dom: ^7.30.3 => 7.30.4 
    @testing-library/jest-dom: ^5.11.10 => 5.12.0 
    @testing-library/react: ^11.2.6 => 11.2.6 
    @testing-library/user-event: ^13.1.2 => 13.1.8 
    @types/jest: ^26.0.22 => 26.0.23 
    amphtml-validator:  undefined ()
    arg:  undefined ()
    async-retry:  undefined ()
    async-sema:  undefined ()
    aws-amplify: ^3.3.26 => 3.3.27 
    babel-jest: ^26.6.3 => 26.6.3 
    bfj:  undefined ()
    cacache:  undefined ()
    cache-loader:  undefined ()
    ci-info:  undefined ()
    comment-json:  undefined ()
    compression:  undefined ()
    conf:  undefined ()
    content-type:  undefined ()
    cookie:  undefined ()
    css-loader:  undefined ()
    debug:  undefined ()
    devalue:  undefined ()
    escape-string-regexp:  undefined ()
    file-loader:  undefined ()
    find-cache-dir:  undefined ()
    find-up:  undefined ()
    framer-motion: ^4 => 4.1.11 
    fresh:  undefined ()
    gzip-size:  undefined ()
    http-proxy:  undefined ()
    ignore-loader:  undefined ()
    is-animated:  undefined ()
    is-docker:  undefined ()
    is-wsl:  undefined ()
    jest: ^26.6.3 => 26.6.3 
    json5:  undefined ()
    jsonwebtoken:  undefined ()
    loader-utils:  undefined ()
    lodash.curry:  undefined ()
    lru-cache:  undefined ()
    mobx: ^6.1.8 => 6.3.0 
    mobx-react: ^7.1.0 => 7.1.0 
    mobx-state-tree: ^5.0.1 => 5.0.1 
    nanoid:  undefined ()
    neo-async:  undefined ()
    next: 10.1.3 => 10.1.3 
    npm-run-all: ^4.1.5 => 4.1.5 
    ora:  undefined ()
    postcss-flexbugs-fixes:  undefined ()
    postcss-loader:  undefined ()
    postcss-preset-env:  undefined ()
    postcss-scss:  undefined ()
    react: 17.0.2 => 17.0.2 
    react-dom: 17.0.2 => 17.0.2 
    react-icons: ^4.2.0 => 4.2.0 
    recast:  undefined ()
    resolve-url-loader:  undefined ()
    sass: ^1.32.8 => 1.32.12 
    sass-loader:  undefined ()
    schema-utils:  undefined ()
    semver:  undefined ()
    send:  undefined ()
    source-map:  undefined ()
    string-hash:  undefined ()
    strip-ansi:  undefined ()
    terser:  undefined ()
    text-table:  undefined ()
    thread-loader:  undefined ()
    unistore:  undefined ()
    web-vitals:  undefined ()
    webpack:  undefined ()
    webpack-sources:  undefined ()
  npmGlobalPackages:
    @aws-amplify/cli: 4.46.1
    n: 7.1.0
    npm: 7.6.3

```

</details>

### Describe the bug

When triggering an Amplify build via previews on a newly opened PR in Github the build completes successfully and the link is provided, however, all of the DynamoDB tables are duplicated and a new Cognito userpool is created for each new pr.

### Expected behavior

I would expect that:
- the same Cognito pools would be used for the provided link
- logins via auth would work in the preview url
- the same tables that were already established would be used for graphql api queries/mutations

### Reproduction steps

open a pr and the preview build settings take it from there

### Code Snippet

Build settings:
```
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --environment main --simple
        // also tried with just - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands: 
        - nvm install 15
        - yarn install
    build:
      commands: 
        - yarn build
  artifacts:
    baseDirectory: out
    files:
      - '**/*'
  cache:
    paths:
      - 'node_modules/**/*'
      - '*/node_modules/**/*'
test:
  phases:
    test:
      commands:
        - yarn test
  artifacts:
    baseDirectory: /
    configFilePath: jest.config.js
    files:
      - '**/*'

```

### Log output

na

### aws-exports.js

```javascript
/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:redacted",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_oyktjNd7a",
    "aws_user_pools_web_client_id": "redacted",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "redacted",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AWS_IAM"
};


export default awsmobile;
```

### Manual configuration

na

### Additional configuration

na

### Additional information and screenshots

![Screen Shot 2021-05-18 at 3 26 19 PM](https://user-images.githubusercontent.com/75633714/118718998-887da580-![Screen Shot 2021-05-18 at 3 26 42 PM](https://user-images.githubusercontent.com/75633714/118719674-633d6700-b7ee-11eb-8ad5-d0f36b9d7eb5.png)
