### ISSUE TITLE
Next.js SSR Build Error

### ISSUE THREAD

**Issue by lindsaybloomsonos** [aws-amplify/amplify-js#9231]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Next.js

### Amplify APIs

Not applicable

### Amplify Categories

Not applicable

### Environment information

<details>

```
Starting SSR Build...
2021-11-16T22:10:34.047Z [ERROR]: Error: pages-manifest not found. Check if `next.config.js` target is set to ''
                                  at CLI.renderError (/root/.npm/_npx/1415/lib/node_modules/@sls-next/-patched/node_modules/@/cli/src/Context.js:325:15)
                                  at Object.runComponents (/root/.npm/_npx/1415/lib/node_modules/@sls-next/-patched/node_modules/@/cli/src/index.js:237:13)
                                  at processTicksAndRejections (internal/process/task_queues.js:97:5)


```

</details>

### Describe the bug

I started seeing this error suddenly without any code changes when deploying my Next.js app. I am able to reproduce this error in multiple Amplify environments without any code changes since the last successful build and deployment.

### Expected behavior

The build is expected to succeed and continue with the `postBuild` steps as follows:

```
2021-11-16T15:37:24.222Z [INFO]: Starting SSR Build...
2021-11-16T15:45:42.200Z [INFO]: SSR Build Complete.
2021-11-16T15:45:43.561Z [INFO]: # Completed phase: build
                                 # Starting phase: postBuild
```

### Reproduction steps

1. Connect a Next.js app in a Github repository to deploy on merges to a branch
2. Merge code into that branch
3. Watch the build logs for the Amplify deployment
4. See if the build step succeeds

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Additional configuration

Build Settings:
```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install --frozen-lockfile
    build:
      commands:
        - yarn build
    postBuild:
      commands:
        - yarn update:cookies --dist-id-key=$COOKIE_OVERRIDE_BRANCH
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
      - .next/cache/**/*
```
